modules/admin/controllers/GymController.php
<?php

namespace app\modules\admin\controllers;

use app\models\District;
use app\models\GymTags;
use app\models\Tag;
use Yii;
use app\models\Gym;
use app\modules\admin\models\GymSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * GymController implements the CRUD actions for Gym model.
 */
class GymController extends AdminController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Gym models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new GymSearch();
        $districtList = Gym::getDistrictList();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'districtList' => $districtList,
        ]);
    }


    /**
     * Creates a new Gym model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Gym();
        $districtList = Gym::getDistrictList();
        $tagList = Gym::getTagList();
        $serviceList = Gym::getServiceList();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
            'districtList' => $districtList,
            'tagList' => $tagList,
            'serviceList' => $serviceList,
        ]);

    }

    /**
     * Updates an existing Gym model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $districtList = Gym::getDistrictList();
        $tagList = Gym::getTagList();
        $serviceList = Gym::getServiceList();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            Yii::$app->session->setFlash('success', "Данные сохранены."); // созданние одноразовых сообщений для пользователя(хранятся в сессии)
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
            'districtList' => $districtList,
            'tagList' => $tagList,
            'serviceList' => $serviceList,
        ]);

    }

    /**
     * Deletes an existing Gym model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Gym model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Gym the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Gym::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/admin/views/gym/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\time\TimePicker;
use Faker\Provider\DateTime;

/* @var $this yii\web\View */
/* @var $model app\models\Gym */
/* @var $form yii\widgets\ActiveForm */
//var_dump($model);
//var_dump($model->gymTags);
//var_dump($model->tags);
//die();
?>

<div class="gym-form">

    <?php $form = ActiveForm::begin(); ?>

    <?php echo $form->field($model, 'gym_name')->textInput(['maxlength' => true]) ?>

    <?php echo $form->field($model, 'description')->textarea(['rows' => 6]) ?>

    <?php echo $form->field($model, 'price')->textInput() ?>

    <?php echo $form->field($model, 'district_id')->dropDownList($districtList) ?>


    <?php echo $form->field($model, 'street')->textInput(['maxlength' => true]) ?>

    <?php echo $form->field($model, 'number')->textInput(['maxlength' => true]) ?>

    <?php echo $form->field($model, 'housing')->textInput(['maxlength' => true]) ?>
    <div class="tags">
<!--                --><?php //echo $form->field($model,'tags')->checkboxList($tags) ?>
        <?php echo $form->field($model, 'tags')->checkboxList($tagList) ?>

    </div>

    <div class="services">
        <?php echo $form->field($model, 'services')->checkboxList($serviceList) ?>
    </div>

    <?php echo $form->field($model, 'start_time')->widget(TimePicker::classname(), [
//        'size' => 'xs',
        'pluginOptions' => [
            'showSeconds' => false,
            'showMeridian' => false,
            'minuteStep' => 15,
            'defaultTime' => '08:00'
//        'defaultTime' => date('H:i', strtotime('-2 hour')),
        ]]); ?>

    <?php echo $form->field($model, 'end_time')->widget(TimePicker::classname(), [
//        'size' => 'xs',
        'pluginOptions' => [
            'showSeconds' => false,
            'showMeridian' => false,
            'minuteStep' => 15,
            'defaultTime' => '22:00'
//        'defaultTime' => date('H:i', strtotime('-2 hour')),
        ]]); ?>

    <div class="form-group">
        <?php echo Html::submitButton('Сохранить', ['class' => 'btn btn-success' ]) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/gym/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\modules\admin\models\GymSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="gym-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'gym_name') ?>

    <?= $form->field($model, 'description') ?>

    <?= $form->field($model, 'price') ?>

    <?= $form->field($model, 'district_id') ?>

    <?php // echo $form->field($model, 'street') ?>

    <?php // echo $form->field($model, 'number') ?>

    <?php // echo $form->field($model, 'housing') ?>

    <?php // echo $form->field($model, 'start_time') ?>

    <?php // echo $form->field($model, 'end_time') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/gym/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Gym */

$this->title = 'Новый зал';
$this->params['breadcrumbs'][] = ['label' => 'Залы', 'url' => ['/admin/gym']];
$this->params['breadcrumbs'][] = ['label' => 'Настройки', 'url' => ['/admin/settings']];
?>
<div class="gym-create">

    <h2><?= Html::encode($this->title) ?></h2>

    <?= $this->render('_form', [
        'model' => $model,
        'districtList' => $districtList,
        'tagList'=>$tagList,
        'serviceList'=>$serviceList,
        ]) ?>

</div>

modules/admin/views/gym/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\modules\admin\models\GymSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Залы';
$this->params['breadcrumbs'][] = ['label' => $this->title, 'url' => ['/admin/gym']];
$this->params['breadcrumbs'][] = ['label' => 'Настройки', 'url' => ['/admin/settings']];


?>
<div class="gym-index">

    <h2 class="text-center"><?= Html::encode($this->title) ?></h2>
    <!--    --><?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p class="text-right">
        <?= Html::a('Создать', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <?php Pjax::begin(); ?>    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'layout' => "{items}\n{pager}",
        'columns' => [
//            ['class' => 'yii\grid\SerialColumn'],
//            'id',
//            'gym_name',
            ['attribute' => 'gym_name',
                'format' => 'html',
                'value' => function ($data) {
                    return Html::a($data->gym_name, Url::toRoute(['gym/update', 'id' => $data->id]), ['title' => 'Редактировать']);
                },
            ],
//            'description:ntext',
            'price',
            [
                'attribute' => 'district_id',
                'format' => 'raw',

                'value' => function ($data) {
                    return $data->getDistrictName();
                },
                'filter' =>$districtList,
            ],
            // 'street',
            // 'number',
            // 'housing',
            // 'start_time',
            // 'end_time',

            ['class' => 'yii\grid\ActionColumn',
//                'template' => '{update}{delete}',
                'urlCreator' => function ($action, $model, $key, $index) {
                    if ($action == 'view') {
                        return Url::to(['/gym/' . $action, 'id' => $model->id]);
                    }else{
                        return Url::to(['/admin/gym/' . $action, 'id' => $model->id]);
                    }
                }
            ],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

modules/admin/views/gym/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Gym */

$this->title = $model->gym_name;
$this->params['breadcrumbs'][] = ['label' => 'Залы', 'url' => ['/admin/gym']];
$this->params['breadcrumbs'][] = ['label' => 'Настройки', 'url' => ['/admin/settings']];
?>
<div class="gym-update">

    <h2><?= Html::encode($this->title) ?></h2>

    <?= $this->render('_form', [
        'model' => $model,
        'districtList' => $districtList,
        'tagList'=>$tagList,
        'serviceList'=>$serviceList,
    ]) ?>

</div>