controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\District;
use app\models\Gym;
use app\models\Service;
use app\models\Tag;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\helpers\Url;
use app\models\RegisterForm;
use app\models\User;
use yii\web\NotFoundHttpException;


class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionGetGyms()
    {
        $gyms = Gym::find()->with(['gymServices','gymTags'])->asArray()->all();
        $services = Service::find()->asArray()->all();
        $tags = Tag::find()->asArray()->all();
        $districts= District::find()->asArray()->all();
        $streets = Gym::find()->select('street')->groupBy('street')->asArray()->all();
//        var_dump($streets);
//        die();
        return json_encode(['gyms'=>$gyms,'services'=>$services,'tags'=>$tags,'districts'=>$districts, 'streets'=>$streets]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect('admin/gym');
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect('/admin/gym');
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Register action
     *
     * @return string|Response
     */
    public function actionRegister()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $model = new RegisterForm();
        if ($model->load(\Yii::$app->request->post()) && $model->validate()) {
            $user = new User();
            $user->username = $model->username;
            $user->email = $model->email;
            $user->role = 'user';
            $user->password = \Yii::$app->security->generatePasswordHash($model->password);
            if ($user->save()) {
                Yii::$app->session->setFlash('success', 'Регистрация прошла успешно'); // созданние одноразовых сообщений для пользователя(хранятся в сессии)
                return Yii::$app->response->redirect('login');
            }
        }
        return $this->render('register', compact('model'));
    }

    public function actionGym($id){

        if (($model = Gym::findOne($id)
            ) !== null) {
            return $this->render('gym', ['model'=>$model]);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

    }


}

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->registerCss('
body{
	font-family: \'Love Ya Like A Sister\', cursive;
}
body{
	background:#eaeaea;
}	
.wrap{
	margin:0 auto;
	width:1000px;
}
.logo{
	text-align:center;
	margin-top:200px;
}
.logo img{
	width:350px;
}
.logo p{
	color:#272727;
	font-size:40px;
	margin-top:1px;
}	
.logo p span{
	color:lightgreen;
}	
.sub a{
	color:#fff;
	background:#272727;
	text-decoration:none;
	padding:10px 20px;
	font-size:13px;
	font-family: arial, serif;
	font-weight:bold;
	-webkit-border-radius:.5em;
	-moz-border-radius:.5em;
	-border-radius:.5em;
}	
.footer{
	color:black;
	position:absolute;
	right:10px;
	bottom:10px;
}	
.footer a{
	color:rgb(114, 173, 38);
}	
');
$this->title = $name;
?>
<!--<div class="site-error">-->
<!---->
<!--    <h1>--><?php //echo Html::encode($this->title) ?><!--</h1>-->
<!---->
<!--    <div class="alert alert-danger">-->
<!--        --><?php //echo nl2br(Html::encode($message)) ?>
<!--    </div>-->
<!---->
<!--    <p>-->
<!--        The above error occurred while the Web server was processing your request.-->
<!--    </p>-->
<!--    <p>-->
<!--        Please contact us if you think this is a server error. Thank you.-->
<!--    </p>-->
<!---->
<!--</div>-->

<div class="wrap">
    <div class="logo">
        <p>OOPS! - Could not Find it</p>
        <img src="img/404.png">

        <!---728x90--->
        <div class="sub">
            <p><a href="#">Back </a></p>
        </div>
    </div>
</div>

views/site/gym.php
<?php

var_dump($model);

views/site/index.php
<?php

/* @var $this yii\web\View */


$this->title = 'SportZal';
$this->registerCssFile('angular-moment-picker\angular-moment-picker.css');
$this->registerJsFile('js\angular.min.js', ['position' => yii\web\View::POS_HEAD]);
$this->registerJsFile('angular-moment-picker\angular-moment-picker.js', ['position' => yii\web\View::POS_HEAD]);

?>
<div class="site-index"  >

    <div ng-app="myApp" ng-controller="getGyms">
        <label for="search_gym_name"> Название: </label><br>
        <input class="form-control" type="text" id="search_gym_name" ng-model="search.gym_name">

        <label for="search_gym_district"> Район: </label>
        <select class="form-control" id="search_gym_district" ng-model="search.district_id">
            <option ng-repeat="x in districts" value="{{x.id}}">{{x.district_name}}</option>
        </select>

        <label for="search_gym_street"> Улица: </label><br>
        <input class="form-control" list="street" type="text" id="search_gym_street" ng-model="search.street">
        <datalist id="street">
            <option ng-repeat="x in streets" value="{{x.street}}">{{x.street}}</option>
        </datalist>
        <b>Направления:</b>
        <div>
            <div ng-repeat="x in tags">
                <label for="search_gym_tags_{{x.id}}">
                    <input id="search_gym_tags_{{x.id}}" ng-click="writeChecked( x.id,'tag' )"
                           type="checkbox">
                    {{x.tag_name}}
                </label>
            </div>
        </div>
        <hr>
        <b>Сервисы:</b>
        <div>
            <div ng-repeat="x in services">
                <label for="search_gym_services_{{x.id}}">
                    <input id="search_gym_services_{{x.id}}" ng-click="writeChecked( x.id,'service' )"
                           type="checkbox">
                    {{x.service_name}}
                </label>
            </div>
        </div>

        <label for="search_gym_price"> Цена: </label><br>
        <input class="form-control" type="text" id="search_gym_price" ng-model="search.price"
               onkeypress="return isNumberKey(event)">
        <br>

        <label>Включить фильтрацию по времени:
            <input type="checkbox" ng-model="checked_filter_time">
        </label><br/>

        <div ng-if="checked_filter_time">
            Открыто с:
            <div class="input-group"
                 locale="ru"
                 set-on-select="false"
                 show-header="false"
                 moment-picker="search_start_time"
                 format="HH:mm">
            <span class="input-group-addon">
                <i class="glyphicon glyphicon-time"></i>
            </span>
                <input class="form-control"
                       placeholder="Select a time"
                       ng-model="search_start_time"
                       ng-blur="writeSearchStartTime(search_start_time)"
                >
            </div>

            Закрывается в:
            <div class="input-group"

                 locale="ru"
                 set-on-select="false"
                 show-header="false"
                 moment-picker="search_end_time"
                 format="HH:mm">
            <span class="input-group-addon">
                <i class="glyphicon glyphicon-time"></i>
            </span>
                <input class="form-control"
                       placeholder="Select a time"
                       ng-model="search_end_time"
                       ng-blur="writeSearchEndTime(search_end_time)"
                >
            </div>

        </div>

        <p>Список залов:</p>
        <div class=" table-responsive" style="overflow: auto; height: 200px">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>Название</th>
                    <th>Район</th>
                    <th>Улица</th>
                    <th>Направление</th>
                    <th>Сервисы</th>
                    <th>Цена,грн</th>
                    <th>время с</th>
                    <th>время по</th>
                </tr>
                </thead>
                <tbody>
                <tr ng-repeat="gym in gyms | filter:filteredGyms | filter:search">

                    <td><a href="/site/gym?id={{gym.id}}"> {{gym.gym_name}}</a></td>
                    <td>{{districts[gym.district_id-1].district_name}}</td>
                    <td>{{gym.street}}</td>

                    <td>
                        <span ng-repeat="serv in gym.gymServices">
                            {{services[serv.service_id -1].service_name}};
                        </span>
                    </td>

                    <td>
                        <span ng-repeat="item in gym.gymTags">
                            {{tags[item.tag_id -1].tag_name}};
                        </span>
                    </td>

                    <td>{{gym.price}}</td>
                    <td>{{gym.start_time | formatTime}}</td>
                    <td>{{gym.end_time | formatTime}}</td>
                </tr>
                </tbody>
            </table>


        </div>

        <script>
            var app = angular.module('myApp', ['moment-picker']);

            Array.prototype.hasAll = function (a) {
                var hash = this.reduce(function (acc, i) {
                    acc[i] = true;
                    return acc;
                }, {});
                return a.every(function (i) {
                    return i in hash;
                });
            };

            // фильтрация на ввод только цифры
            function isNumberKey(evt) {
                var charCode = (evt.which) ? evt.which : event.keyCode;
                if (charCode > 31 && (charCode < 48 || charCode > 57))
                    return false;
                return true;
            }


            app.filter('formatTime', function ($filter) {
                return function (time, format) {
                    var parts = time.split(':');
                    var date = new Date(0, 0, 0, parts[0], parts[1], parts[2]);
                    return $filter('date')(date, format || 'HH:mm');
                };
            });


            app.controller('getGyms', function ($scope, $http) {

                $scope.search_start_time = "10:00";
                $scope.search_end_time = "20:00";


                $scope.search_checked = {
                    'tag': [],
                    'service': []
                };

                $scope.checked_filter_time = false;

                $scope.writeSearchStartTime = function (search_start_time) {
                    $scope.search_start_time = search_start_time;
                };

                $scope.writeSearchEndTime = function (search_end_time) {
                    $scope.search_end_time = search_end_time;
                };

                $scope.writeChecked = function (colour, name) {
                    var i = $.inArray(colour, $scope.search_checked[name]);
                    if (i > -1) {
                        $scope.search_checked[name].splice(i, 1);
                    } else {
                        $scope.search_checked[name].push(colour);
                    }
                };


                $scope.filteredGyms = function (gym) {
                    var flag = true;
                    // почему то тут он проходит в два раза больше чем количество залов
                    console.log("test2");
                    if ($scope.search_checked['tag'].length > 0) {
                        var arr_tags = [];
                        //создаем массив тегов, которые есть в конкретном зале
                        // создаем массив tag_id из связанной таблицы gym.gymTags
                        gym.gymTags.map(function (item) {
                            arr_tags[arr_tags.length] = item.tag_id;
                        });

                        //проверяем вхождение всех выбранных тегов в в теги зала
                        if (arr_tags.hasAll($scope.search_checked['tag'])) {
                            flag = true;
                        } else {
                            //не возвращает залы, если в них нет всех выбранных тегов
                            flag = false;
                        }
                    }

                    if (($scope.search_checked['service'].length > 0) && (flag)) {
                        var arr_services = [];
                        //создаем массив тегов, которые есть в конкретном зале
                        // создаем массив tag_id из связанной таблицы gym.gymTags
                        gym.gymServices.map(function (item) {
                            arr_services[arr_services.length] = item.service_id;
                        });

                        //проверяем вхождение всех выбранных тегов в в теги зала
                        if (arr_services.hasAll($scope.search_checked['service'])) {
                            flag = true;
                        } else {
                            //не возвращает залы, если в них нет всех выбранных тегов
                            flag = false;
                        }
                    }

                    if ($scope.checked_filter_time && (($scope.search_start_time) && ($scope.search_end_time))) {
//                        console.log($scope.checked_filter_time);
                        // тут вообще 60 раз проходит
                        console.log("test");
                        var arr_gym_start_time = (gym.start_time).split(":");
                        var gym_start_time = new Date().setHours(arr_gym_start_time[0], arr_gym_start_time[1]);

                        var arr_gym_end_time = (gym.end_time).split(":");
                        var gym_end_time = new Date().setHours(arr_gym_end_time[0], arr_gym_end_time[1]);

                        var arr_search_start_time = ($scope.search_start_time).split(":");
                        var search_start_time = new Date().setHours(arr_search_start_time[0], arr_search_start_time[1]);

                        var arr_search_end_time = ($scope.search_end_time).split(":");
                        var search_end_time = new Date().setHours(arr_search_end_time[0], arr_search_end_time[1]);

                        // очень много раз проходит по этой ветке!!!
//                        console.log("test");
//                        console.log(gym.end_time,"  ",$scope.search_end_time);
//                        console.log(gym_end_time,"  ",search_end_time);
//                        console.log(gym_end_time>search_end_time);
                        if (
                            ((gym_start_time <= search_start_time))// || (gym_start_time === search_start_time))
                            &&
                            ((gym_end_time >= search_end_time))// || (gym_end_time === search_end_time))
                        ) {
                            flag = true
                        } else {
                            flag = false
                        }
                    }

                    if (flag === true) {
                        return gym;
                    } else {
                        return false;
                    }

                };


                $http({
                    method: "GET",
                    url: "/site/get-gyms"
                })
                    .then(function (response) {
                        $scope.gyms = response.data.gyms;
                        $scope.services = response.data.services;
                        $scope.tags = response.data.tags;
                        $scope.districts = response.data.districts;
                        $scope.streets = response.data.streets;
                    });

            });
        </script>

    </div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Bxод';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>


    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>


        <?= $form->field($model, 'email')->input('email')->textInput(['autofocus' => true]); ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>


</div>

views/site/register.php
<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Вход';
?>

    <div class="site-register">

<!--        <h1>--><?php //echo Html::encode($this->title) ?><!--</h1>-->
        <h3>Форма регистрации</h3>
        <br>
        <a href="/login">уже зарегистрированны</a>

        <?php $form = ActiveForm::begin([
            'id' => 'register-form',
            'method' => 'post',

            'layout' => 'horizontal',
            'fieldConfig' => [
                'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
                'labelOptions' => ['class' => 'col-lg-1 control-label'],
            ],
        ]); ?>

        <?php echo $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'email')->input('email'); ?>

        <?= $form->field($model, 'password')->passwordInput() ?>


        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Регистрация', ['class' => 'btn btn-success', 'name' => 'register-button']) ?>
            </div>
        </div>

        <?php ActiveForm::end(); ?>

    </div>